template = ""
rev_id = 4
template_sha = "87be02986858c4b7ae5e8613b6f951c3c209b221"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "ru"
__UND2C_TRG__ = "sjt"
__UNDEFINED_SOURCE__ = "Russian"
__UNDEFINED_TARGET__ = "Ter Saami"
__UND_SRC__ = "rus"
__UND_TRG__ = "sjt"
